openapi: 3.0.3
info:
  title: API Port de plaisance Russell
  version: 0.1.0
servers:
  - url: http://localhost:3000
paths:
  /health:
    get:
      summary: Ping
      responses:
        "200":
          description: OK
